# Generated by Django 2.2.6 on 2019-11-08 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191108_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(blank=True, null=True, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
