export const AUTH_START = 'AUTH_START';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const PROJECT_LIST_LOADING = 'PROJECT_LIST_LOADING';

export const PROJECT_LIST_LOADED = 'PROJECT_LIST_LOADED';

export const PROJECT_LIST_ERROR = 'PROJECT_LIST_ERROR';

export const PROJECT_ADDED = 'PROJECT_ADDED';

export const PROJECT_DETAIL_LOADING = 'PROJECT_DETAIL_LOADING';

export const PROJECT_DETAIL_LOADED = 'PROJECT_DETAIL_LOADED';

export const PROJECT_DETAIL_ERROR = 'PROJECT_DETAIL_ERROR';
